import React, { useState, useEffect } from "react";
import { useValidation } from "@/hooks/useValidation";
import Input from "@/components/ui/Input";
import Button from "@/components/ui/Button";
import { useAuth } from "@/hooks/useAuth";
import { useZxing } from "react-zxing";

const ValidationPortal: React.FC = () => {
  const [codeInput, setCodeInput] = useState("");
  const [showQRScanner, setShowQRScanner] = useState(false);
  const [isCameraReady, setIsCameraReady] = useState(false);
  const [cameraError, setCameraError] = useState<string | null>(null);
  const [stream, setStream] = useState<MediaStream | null>(null);

  const { state, result, errorMessage, validate, validateQR, history, reset } = useValidation();
  const { logout, user } = useAuth();

  const officerName = user
    ? `${user.firstName ?? ""} ${user.lastName ? user.lastName.charAt(0) + "." : ""}`
    : "Guest";

  // 🔹 Manual validation
  const handleValidationSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (codeInput.length === 5 && state !== "loading") {
      validate(codeInput);
    }
  };

  // 🔹 QR validation
  const handleQRScan = async (data: string) => {
    if (data) {
      stopCamera();
      setShowQRScanner(false);
      await validateQR(data);
    }
  };

  // 🔹 Setup camera with zxing
  const { ref: videoRef } = useZxing({
    onDecodeResult(result) {
      if (result) handleQRScan(result.getText());
    },
    paused: !showQRScanner,
  });

  // 🔹 Start camera
  const startCamera = async () => {
    try {
      setCameraError(null);
      const mediaStream = await navigator.mediaDevices.getUserMedia({
        video: { facingMode: "environment" },
      });
      const video = videoRef.current as HTMLVideoElement | null;
      if (video) {
        video.srcObject = mediaStream;
        video.play();
      }
      setStream(mediaStream);
      setIsCameraReady(true);
    } catch (err) {
      console.error("Camera access error:", err);
      setCameraError("Unable to access camera. Please check permissions.");
    }
  };

  // 🔹 Stop camera
  const stopCamera = () => {
    if (stream) {
      stream.getTracks().forEach((track) => track.stop());
      setStream(null);
      setIsCameraReady(false);
    }
  };

  useEffect(() => {
    if (showQRScanner) startCamera();
    else stopCamera();
    return () => stopCamera();
  }, [showQRScanner]);

  // 🔹 Close modal manually
  const closeModal = () => {
    reset();
    setCodeInput("");
  };

  // 🔹 Keep modal stable: don’t reset automatically while validating
  useEffect(() => {
    // We removed the "reset when typing" here — it caused flicker issues
  }, []);

  // 🔹 Render Modal
  const renderModal = () => {
    if (state === "success" && result) {
      return (
        <div style={overlayStyle}>
          <div style={{ ...cardStyle, borderColor: "#28a745", background: "#eaffea" }}>
            <h2 style={{ color: "#155724" }}>ACCESS GRANTED ✅</h2>
            <p>Generated by: <strong>{result.residentName}</strong></p>
            <p>
              Home:{" "}
              <strong>
                {`${result.homeDetails?.plotNumber ?? ""} ${result.homeDetails?.street ?? ""}`}
              </strong>
            </p>
            <p>Visitor: <strong>{result.visitorName}</strong></p>
            <Button onClick={closeModal}>OK</Button>
          </div>
        </div>
      );
    }

    if (state === "denied" || state === "error") {
      return (
        <div style={overlayStyle}>
          <div style={{ ...cardStyle, borderColor: "#dc3545", background: "#ffeaea" }}>
            <h2 style={{ color: "#a00000" }}>ACCESS DENIED ❌</h2>
            <p>{errorMessage || "Invalid access code"}</p>
            <Button onClick={closeModal} variant="danger">OK</Button>
          </div>
        </div>
      );
    }

    return null;
  };

  return (
    <div style={pageStyle}>
      {/* HEADER */}
      <header style={headerStyle}>
        <div>
          <h1 style={{ fontSize: "20px" }}>Security Validation Portal</h1>
          <p style={{ fontSize: "12px" }}>Officer: <strong>{officerName}</strong></p>
        </div>
        <div style={{ textAlign: "right" }}>
          <p style={{ fontSize: "12px", marginBottom: "4px" }}>
            {new Date().toLocaleDateString("en-US", { weekday: "short", month: "short", day: "numeric" })}{" "}
            {new Date().toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" })}
          </p>
          <button onClick={logout} style={logoutBtnStyle}>LOGOUT</button>
        </div>
      </header>

      {/* FORM */}
      <main style={formContainerStyle}>
        <h3>Validate Access Code</h3>
        <form onSubmit={handleValidationSubmit} style={formStyle}>
          <Input
            label=""
            type="text"
            maxLength={5}
            value={codeInput.toUpperCase()}
            onChange={(e) => setCodeInput(e.target.value.toUpperCase())}
            placeholder="Enter Access Code"
            style={inputStyle}
          />
          <Button type="submit" disabled={state === "loading"} style={buttonStyle}>
            {state === "loading" ? "Validating..." : "VALIDATE"}
          </Button>
        </form>

        <Button onClick={() => setShowQRScanner(!showQRScanner)} style={{ marginTop: "10px" }}>
          {showQRScanner ? "Close Scanner" : "Scan QR Code"}
        </Button>
      </main>

      {/* QR SCANNER */}
      {showQRScanner && (
        <div style={scannerContainerStyle}>
          <video ref={videoRef} autoPlay playsInline style={videoStyle} />
          {!isCameraReady && !cameraError && <p style={infoText}>Activating camera...</p>}
          {cameraError && <p style={errorText}>{cameraError}</p>}
          {isCameraReady && !cameraError && (
            <p style={infoText}>Scanning... Hold your QR code steady.</p>
          )}
        </div>
      )}

      {/* RECENT VALIDATIONS */}
      <section style={tableSectionStyle}>
        <h3>Recent Validations</h3>
        <div style={{ overflowX: "auto" }}>
          <table style={tableStyle}>
            <thead>
              <tr>
                <th>Time</th>
                <th>Code</th>
                <th>Visitor</th>
                <th>Resident</th>
                <th>Status</th>
              </tr>
            </thead>
            <tbody>
              {history.length > 0 ? (
                history.slice(0, 5).map((log) => (
                  <tr key={log.id}>
                    <td>{new Date(log.timestamp).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" })}</td>
                    <td>{log.code}</td>
                    <td>{log.visitorName}</td>
                    <td>{log.residentName || "N/A"}</td>
                    <td
                      style={{
                        color: log.status.toLowerCase() === "granted" ? "#28a745" : "#dc3545",
                        fontWeight: 600,
                        textTransform: "uppercase",
                      }}
                    >
                      {log.status.toUpperCase()}
                    </td>
                  </tr>
                ))
              ) : (
                <tr>
                  <td colSpan={5} style={{ textAlign: "center", padding: "15px", color: "#777" }}>
                    No recent validations
                  </td>
                </tr>
              )}
            </tbody>
          </table>
        </div>
      </section>

      {/* MODAL */}
      {renderModal()}
    </div>
  );
};

export default ValidationPortal;

/* ---------- STYLES ---------- */
const pageStyle: React.CSSProperties = {
  minHeight: "100vh",
  backgroundColor: "#f4f7fb",
  fontFamily: "Inter, sans-serif",
  padding: "15px",
};

const headerStyle: React.CSSProperties = {
  backgroundColor: "#ffffff",
  borderBottom: "2px solid #007bff",
  padding: "10px 15px",
  display: "flex",
  justifyContent: "space-between",
  alignItems: "center",
  borderRadius: "8px",
  marginBottom: "25px",
  flexWrap: "wrap",
  boxShadow: "0 2px 6px rgba(0, 0, 0, 0.1)",
};

const logoutBtnStyle: React.CSSProperties = {
  background: "none",
  border: "1px solid #007bff",
  borderRadius: "6px",
  color: "#007bff",
  cursor: "pointer",
  padding: "6px 10px",
  fontSize: "12px",
  fontWeight: 600,
};

const formContainerStyle: React.CSSProperties = {
  background: "#fff",
  borderRadius: "10px",
  padding: "30px",
  boxShadow: "0 4px 12px rgba(0,0,0,0.1)",
  maxWidth: "1000px",
  margin: "0 auto 20px auto",
  textAlign: "center",
};

const formStyle: React.CSSProperties = {
  display: "flex",
  flexWrap: "wrap",
  gap: "12px",
  justifyContent: "center",
  alignItems: "center",
  marginTop: "10px",
};

const inputStyle: React.CSSProperties = {
  flex: "1 1 200px",
  minWidth: "180px",
  maxWidth: "260px",
};

const buttonStyle: React.CSSProperties = {
  padding: "6px 12px",
  height: "40px",
  fontSize: "13px",
  fontWeight: 600,
  border: "2px solid #007bff",
  flex: "0 1 auto",
};

const scannerContainerStyle: React.CSSProperties = {
  marginTop: "15px",
  display: "flex",
  flexDirection: "column",
  alignItems: "center",
  justifyContent: "center",
  width: "100%",
  maxWidth: "420px",
  marginInline: "auto",
};

const videoStyle: React.CSSProperties = {
  width: "100%",
  height: "auto",
  borderRadius: "12px",
  border: "2px solid #007bff",
  boxShadow: "0 0 10px rgba(0,0,0,0.2)",
  backgroundColor: "#000",
};

const infoText: React.CSSProperties = {
  marginTop: "10px",
  color: "#007bff",
  fontSize: "0.9rem",
  textAlign: "center",
};

const errorText: React.CSSProperties = {
  marginTop: "10px",
  color: "red",
  textAlign: "center",
};

const tableSectionStyle: React.CSSProperties = {
  background: "#fff",
  borderRadius: "10px",
  padding: "30px",
  boxShadow: "0 4px 12px rgba(0,0,0,0.1)",
  maxWidth: "1030px",
  margin: "0 auto 30px auto",
};

const tableStyle: React.CSSProperties = {
  width: "100%",
  borderCollapse: "collapse",
  fontSize: "14px",
};

const overlayStyle: React.CSSProperties = {
  position: "fixed",
  top: 0,
  left: 0,
  width: "100%",
  height: "100%",
  backgroundColor: "rgba(0, 0, 0, 0.6)",
  display: "flex",
  justifyContent: "center",
  alignItems: "center",
  zIndex: 2000,
  padding: "20px",
};

const cardStyle: React.CSSProperties = {
  borderRadius: "12px",
  padding: "25px 35px",
  textAlign: "center",
  maxWidth: "90%",
  width: "400px",
  boxShadow: "0 6px 20px rgba(0,0,0,0.3)",
};
