import React, { useState, useEffect } from "react";
import { useValidation } from "@/hooks/useValidation";
import Input from "@/components/ui/Input";
import Button from "@/components/ui/Button";
import { useAuth } from "@/hooks/useAuth";
import { useZxing } from "react-zxing";



const ValidationPortal: React.FC = () => {
  const [codeInput, setCodeInput] = useState("");
  const [showQRScanner, setShowQRScanner] = useState(false);
const { state, result, errorMessage, validate, validateQR, history, reset } = useValidation();
  const { logout, user } = useAuth();

  const officerName = user
    ? `${user.firstName ?? ""} ${user.lastName ? user.lastName.charAt(0) + "." : ""}`
    : "Guest";

  // Reset when typing a new code
  useEffect(() => {
    if (state !== "idle" && codeInput.length > 0) reset();
  }, [codeInput, state, reset]);

  // Manual code validation
  const handleValidationSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (codeInput.length === 5 && state !== "loading") {
      validate(codeInput);
    }
  };

  // QR scan validation
  const handleQRScan = async (data: string) => {
  if (data) {
    setShowQRScanner(false);
    await validateQR(data);
  }
};


  const closeModal = () => {
    reset();
    setCodeInput("");
  };

  const renderModal = () => {
    if (state === "success" && result) {
      return (
        <div style={overlayStyle}>
          <div style={cardSuccess}>
            <h2>ACCESS GRANTED ✅</h2>
            <p>Generated by: <strong>{result.residentName}</strong></p>
            <p>Home: <strong>{`${result.homeDetails?.plotNumber ?? ""} ${result.homeDetails?.street ?? ""}`}</strong></p>
            <p>Visitor: <strong>{result.visitorName}</strong></p>
            <Button onClick={closeModal} >OK</Button>
          </div>
        </div>
      );
    }

    if (state === "denied" || state === "error") {
      return (
        <div style={overlayStyle}>
          <div style={cardError}>
            <h2>ACCESS DENIED ❌</h2>
            <p>{errorMessage || "Invalid access code"}</p>
            <Button onClick={closeModal} variant="danger" style={{ marginTop: "15px" }}>OK</Button>
          </div>
        </div>
      );
    }
    return null;
  };

  return (
    <div style={pageStyle}>
      {/* HEADER */}
      <header style={headerStyle}>
        <div>
          <h1 style={{ fontSize: "20px" }}>Security Validation Portal</h1>
          <p style={{ fontSize: "12px" }}>Officer: <strong>{officerName}</strong></p>
        </div>
        <div>
          <p style={{ fontSize: "12px", marginBottom: "4px" }}>
            {new Date().toLocaleDateString("en-US", { weekday: "short", month: "short", day: "numeric" })}{" "}
            {new Date().toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" })}
          </p>
          <button onClick={logout} style={logoutBtnStyle}>LOGOUT</button>
        </div>
      </header>

      {/* VALIDATION FORM */}
    <main style={formContainerStyle}>
        <h3>Validate Access Code</h3>

        <form onSubmit={handleValidationSubmit} style={formStyle}>
          <Input
            label="Enter Code"
            type="text"
            maxLength={5}
            value={codeInput.toUpperCase()}
            onChange={(e) => setCodeInput(e.target.value.toUpperCase())}
            placeholder="e.g., A1B2C"
          />
          <Button type="submit" disabled={state === "loading"} style={{ padding: "10px", height: "40%" }}>
            VALIDATE
          </Button>
        </form>

        <p style={{ marginTop: "10px" }}>OR</p>

        <Button onClick={() => setShowQRScanner(!showQRScanner)}>
          {showQRScanner ? "Close Scanner" : "Scan QR Code"}
        </Button>

      </main>
      {showQRScanner && (
  <div style={{ marginTop: "15px" }}>
    <video
      ref={ref => {
        if (ref) {
          const { ref: videoRef } = useZxing({
            onDecodeResult(result) {
              handleQRScan(result.getText());
            },
          });
          videoRef.current = ref;
        }
      }}
      style={{
        width: "100%",
        borderRadius: "8px",
        border: "2px solid #007bff",
      }}
    />
    <p style={{ marginTop: "8px", color: "#007bff", fontSize: "13px" }}>
      Scanning... hold QR code steady in front of the camera
    </p>
  </div>
)}

      
      {/* RECENT VALIDATIONS */}
      <section style={tableSectionStyle}>
        <h3>Recent Validations</h3>
        <table style={tableStyle}>
          <thead>
            <tr>
              <th>Time</th>
              <th>Code</th>
              <th>Visitor</th>
              <th>Resident</th>
              <th>Status</th>
            </tr>
          </thead>
          <tbody>
            {history.length > 0 ? (
              history.slice(0, 5).map((log) => (
                <tr key={log.id}>
                  <td>{new Date(log.timestamp).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" })}</td>
                  <td>{log.code}</td>
                  <td>{log.visitorName}</td>
                  <td>{log.residentName || "N/A"}</td>
                  <td style={{ color: log.status === "GRANTED" ? "#28a745" : "#dc3545" }}>{log.status}</td>
                </tr>
              ))
            ) : (
              <tr>
                <td colSpan={5} style={{ textAlign: "center", padding: "15px", color: "#777" }}>
                  No recent validations
                </td>
              </tr>
            )}
          </tbody>
        </table>
      </section>

      {/* FEEDBACK MODAL */}
      {renderModal()}
    </div>
  );
};

export default ValidationPortal;

/* ---------- STYLES ---------- */
const pageStyle: React.CSSProperties = {
  minHeight: "100vh",
  backgroundColor: "#f4f7fb",
  fontFamily: "Inter, sans-serif",
  padding: "0px",
};

const headerStyle: React.CSSProperties = {
  backgroundColor: "#ffffff",
  borderBottom: "2px solid #007bff",
  padding: "10px 15px",
  display: "flex",
  justifyContent: "space-between",
  alignItems: "center",
  borderRadius: "8px",
  marginBottom: "30px",
  boxShadow: "0 2px 6px rgba(0, 0, 0, 0.1)",
};

const logoutBtnStyle: React.CSSProperties = {
  background: "none",
  border: "1px solid #007bff",
  borderRadius: "6px",
  color: "#007bff",
  cursor: "pointer",
  padding: "6px 10px",
  fontSize: "12px",
  fontWeight: "600",
};

const formContainerStyle: React.CSSProperties = {
  background: "#fff",
  borderRadius: "10px",
  padding: "25px",
  boxShadow: "0 4px 12px rgba(0,0,0,0.1)",
  maxWidth: "480px",
  margin: "0 auto 30px auto",
  textAlign: "center",
};

const formStyle: React.CSSProperties = {
  display: "flex",
  gap: "12px",
  justifyContent: "center",
  marginTop: "10px",
};

const tableSectionStyle: React.CSSProperties = {
  background: "#fff",
  borderRadius: "10px",
  padding: "20px",
  boxShadow: "0 4px 12px rgba(0,0,0,0.1)",
  maxWidth: "700px",
  margin: "0 auto",
};

const tableStyle: React.CSSProperties = {
  width: "100%",
  borderCollapse: "collapse",
  fontSize: "14px",
};

const overlayStyle: React.CSSProperties = {
  position: "fixed",
  top: 0,
  left: 0,
  width: "100%",
  height: "100%",
  backgroundColor: "rgba(0, 0, 0, 0.5)",
  display: "flex",
  justifyContent: "center",
  alignItems: "center",
  zIndex: 1000,
};

const cardSuccess: React.CSSProperties = {
  background: "#eaffea",
  border: "3px solid #28a745",
  borderRadius: "12px",
  padding: "25px 35px",
  textAlign: "center",
  color: "#155724",
  boxShadow: "0 6px 20px rgba(0,0,0,0.2)",
};

const cardError: React.CSSProperties = {
  background: "#ffeaea",
  border: "3px solid #dc3545",
  borderRadius: "12px",
  padding: "25px 35px",
  textAlign: "center",
  color: "#a00000",
  boxShadow: "0 6px 20px rgba(0,0,0,0.2)",
};
